### ISSUE TITLE
Just checking in

### ISSUE THREAD

**Issue by yolapop** [JerzyPuchalski/Android-DPI-Calculator#4]
This plugin will be very useful but, after installing, I couldn't use it because

```
11:48:36 PM PluginException: cannot create class "net.nerrd.intellij.plugin.dpicalculator.action.DpiCalculatorAction" [Plugin: net.nerrd.intellij.plugin.dpicalculator]
```

Is there anything wrong with my Studio?

**Comment by JerzyPuchalski** [comment]
Hey there! Did you used jar file attached on github or installed it via
Android Studio Plugins repository?
BR,
Jerzy

2015-07-05 18:57 GMT+02:00 Yolanda Septiana notifications@github.com:

**Comment by yolapop** [comment]
I installed from this https://github.com/JerzyPuchalski/Android-DPI-Calculator/blob/master/AndroidDpiCalculator.jar

**Comment by JerzyPuchalski** [comment]
It shouldn't make a difference, but can you try to install it from Android
Studio (Settings / Plugins / Browse Repositories / Android DPI Calculator)?

2015-07-05 21:06 GMT+02:00 Yolanda Septiana notifications@github.com:

**Comment by vwmattr** [comment]
I installed from Android Studio (Settings / Plugins / Browse Repositories / Android DPI Calculator) and I am getting a similar error. Here's the stack trace I'm seeing:

```
cannot create class "net.nerrd.intellij.plugin.dpicalculator.action.DpiCalculatorAction" [Plugin: net.nerrd.intellij.plugin.dpicalculator]
com.intellij.diagnostic.PluginException: cannot create class "net.nerrd.intellij.plugin.dpicalculator.action.DpiCalculatorAction" [Plugin: net.nerrd.intellij.plugin.dpicalculator]
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:176)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convert(ActionManagerImpl.java:516)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:496)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:489)
    at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:354)
    at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:312)
    at com.intellij.openapi.actionSystem.impl.Utils.hasChildrenWithState(Utils.java:225)
    at com.intellij.openapi.actionSystem.impl.Utils.hasEnabledChildren(Utils.java:209)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:147)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:86)
    at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:280)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:281)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.access$400(ActionMenu.java:41)
    at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:235)
    at javax.swing.JMenu.fireMenuSelected(JMenu.java:1028)
    at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1107)
    at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:333)
    at javax.swing.DefaultButtonModel.setSelected(DefaultButtonModel.java:215)
    at javax.swing.JMenu.setSelected(JMenu.java:294)
    at com.apple.laf.ScreenMenu$1.run(ScreenMenu.java:117)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
    at apple.awt.CToolkit$CPeerEvent.dispatch(CToolkit.java:1221)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: com.intellij.diagnostic.PluginException: net/nerrd/intellij/plugin/dpicalculator/action/DpiCalculatorAction : Unsupported major.minor version 52.0 [Plugin: net.nerrd.intellij.plugin.dpicalculator]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:152)
    ... 37 more
Caused by: java.lang.UnsupportedClassVersionError: net/nerrd/intellij/plugin/dpicalculator/action/DpiCalculatorAction : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:259)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:255)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:231)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:124)
    ... 43 more
```
