### ISSUE TITLE
Err after install and restart Android Studio

### ISSUE THREAD

**Issue by fuechter** [JerzyPuchalski/Android-DPI-Calculator#7]
After install plugin, the same don't display on menu **Tools -> Android -> DPI Calcular**, but in Event Logs display some errors of plugin.... is a bug or lack I install any dependency?

![err](https://s3.amazonaws.com/f.cl.ly/items/350E2B3K2S131Q3x0I3J/Captura%20de%20Tela%202015-07-05%20a%CC%80s%2018.13.28.png)

**Comment by brucetoo** [comment]
same problem in android studio

**Comment by lvleo** [comment]
me too

**Comment by JerzyPuchalski** [comment]
Seems that the problem occurs on newer versions of Android Studio on OSX where in menu bar there is no _Tools_ / _Android_ branch. On GNU/Linux and Windows it exists so there is no problem. I'll try to work on some solution soon!

**Comment by sbakhtiarov** [comment]
Same error on Windows / Android Studio AI-141.2024585
Null child action in group Android () of class class org.jetbrains.android.actions.AndroidToolsActionGroup, id=net.nerrd.intellij.plugin.DpiCalculatorAction

**Comment by paolop** [comment]
Same for me: Android Studio 1.2.2 on mac os x 10.10.3

19:04:59 PluginException: cannot create class "net.nerrd.intellij.plugin.dpicalculator.action.DpiCalculatorAction" [Plugin: net.nerrd.intellij.plugin.dpicalculator]

**Comment by inferjay** [comment]
me too

Mac OSX 10.10.4/Android Studio AI-141.2024585

Error log：

Null child action in group Android () of class class org.jetbrains.android.actions.AndroidToolsActionGroup, id=net.nerrd.intellij.plugin.DpiCalculatorAction
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
    at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:356)
    at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:312)
    at com.intellij.openapi.actionSystem.impl.Utils.hasChildrenWithState(Utils.java:225)
    at com.intellij.openapi.actionSystem.impl.Utils.hasEnabledChildren(Utils.java:209)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:147)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:86)
    at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:280)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:281)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.access$400(ActionMenu.java:41)
    at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:235)
    at javax.swing.JMenu.fireMenuSelected(JMenu.java:1028)
    at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1107)
    at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:333)
    at javax.swing.DefaultButtonModel.setSelected(DefaultButtonModel.java:215)
    at javax.swing.JMenu.setSelected(JMenu.java:294)
    at com.apple.laf.ScreenMenu$1.run(ScreenMenu.java:117)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
    at apple.awt.CToolkit$CPeerEvent.dispatch(CToolkit.java:1221)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
    at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:356)
    at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:312)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:125)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:86)
    at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:280)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:281)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.access$400(ActionMenu.java:41)
    at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:235)
    at javax.swing.JMenu.fireMenuSelected(JMenu.java:1028)
    at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1107)
    at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:333)
    at javax.swing.DefaultButtonModel.setSelected(DefaultButtonModel.java:215)
    at javax.swing.JMenu.setSelected(JMenu.java:294)
    at com.apple.laf.ScreenMenu$1.run(ScreenMenu.java:117)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
    at apple.awt.CToolkit$CPeerEvent.dispatch(CToolkit.java:1221)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by shaobin0604** [comment]
same issue:

Android Studio 1.2.2 on Ubuntu 12.04 x64

error log

```
11:28:55 AM PluginException: cannot create class "net.nerrd.intellij.plugin.dpicalculator.action.DpiCalculatorAction" [Plugin: net.nerrd.intellij.plugin.dpicalculator]
```

**Comment by ArchangelXu** [comment]
me too
Intellij Idea 14.1.4 Windows7
PluginException: cannot create class "net.nerrd.intellij.plugin.dpicalculator.action.DpiCalculatorAction" [Plugin: net.nerrd.intellij.plugin.dpicalculator]

**Comment by fiattt** [comment]
me too
![image](https://cloud.githubusercontent.com/assets/1531440/9193427/ddd0eb08-4045-11e5-9400-6451dc0357d6.png)
